### PR TITLE
IANA media type request for application/activity+json

### PR DESCRIPTION
**Pull request by gobengo**
To act on #424, I filled out the form to register `application/activity+json` with the IANA.

They sent me some feedback, which I acted upon just now with [this change](https://github.com/w3c/activitystreams/commit/b2319fd96710ed9be4bba49f7e795c559df643d9).

I will now send this PR/file back to them for a final review.

I think it would be useful to have contributions or +1 from at least one of the editors, so /cc @jasnell @evanp

### CODE REVIEW

**Comment by nightpool** [comment]
There was some discussion around the ActivityPub community about fragment identifiers. I don't want to say too much since I don't know what supposed to go into this document, but we might want to double check what JSON-LD has in their media type and go with something similar to that.

**Comment by gobengo** [comment]
> we might want to double check what JSON-LD has in their media type and go with something similar to that.

I don't think we should claim anything in this IANA request that's not mentioned in the AS2 spec, and fragment identifiers aren't.

I agree with your instinct that it would make sense for AS2 to have same fragment identifier interpretation as JSON-LD (defer to [rdf](https://www.w3.org/TR/rdf11-concepts/#section-fragID)). However, I think the best place for that discussion/vote is as an ammendment to activitystreams-core, not this IANA media type application.

**Comment by cwebber** [comment]
I agree, AS2 "refers upstream" to json-ld, so effectively in this application fragment identifiers are what the json-ld community does.  If any amendment is required, I would say that.

We can specify that more clearly in the AS2 application what that means, or any revisions to that present policy, outside of this particular application.

Thank you for submitting this @gobengo !

**Comment by gobengo** [comment]
From IANA

> If more changes based on community or editor feedback might be forthcoming, the reviewers will want us to hold off on sending them an edited template.
> 
> Can you let us know when the community review of this version of the template is complete?

If there is not Editor consensus by next CG meeting on 2/28, in that meeting I will make a proposal to resubmit what's in this PR for further IANA review.

If you think there should be changes not reflected here, make PRs ASAP to gobengo:iana-request that others can weigh in on or explicitly request that I make certain changes myself.

**Pull request closed without merging**
