### PR TITLE
AS2 Ontology: Added relationships defined in JSON-LD context.

### PR DESCRIPTION
**Pull request by steve-bate**

### CODE REVIEW

**Review by csarven — CHANGES_REQUESTED** [review]
I think there is some grounds to not introduce this into the RDF. AFAICT, https://github.com/w3c/activitystreams/issues/406 was resolved with the understanding to remove these classes from the normative specs however they were not removed from the JSON-LD.

I suggest closing this PR.

See follow up: https://github.com/w3c/activitystreams/pull/574 .

**Comment by steve-bate** [comment]
> I think there is some grounds to not introduce this into the RDF. AFAICT, #406 was resolved with the understanding to remove these classes from the normative specs however they were not removed from the JSON-LD context.
> 
> I suggest closing this PR.
> 
> See follow up: #574 .

I think it makes sense to at least add comments to the OWL referencing the pending issue to provide a description of the situation to others comparing the OWL model with the JSON-LD context. I'll make that change.

**Comment by csarven** [comment]
I suggest that we process PR 574 before processing this PR 566.

I don't see the urgency in adding information to the OWL - it is not just comments but actual statements - even if temporarily, when it appears to be that information shouldn't be there to begin with.

If 574 is merged, we'll have to undo 566.

If 574 is rejected, and that the relationships somehow should be re-introduced/defined in the Vocabulary, only then 566 is useful. My preference would be to leave out the information for the time being instead of introducing information that in all likelihood doesn't belong.

**Comment by steve-bate** [comment]
> I suggest that we process PR 574 before processing this PR 566.
> 
> I don't see the urgency in adding information to the OWL - it is not just comments but actual statements - even if temporarily, when it appears to be that information shouldn't be there to begin with.

Fair enough. I maintain [a fork of the ontology](https://github.com/steve-bate/activitypub-ontology) and I'll do active maintenance on that to keep in sync with the current JSON-LD normative context (as much as possible). It's easy to change it if and when the normative JSON-LD context issue is addressed (it's been almost 7 years now).

> If 574 is merged, we'll have to undo 566.

That's true, but is it a problem? My understanding (based on historical @jasnell comments) is that the OWL ontology is intentionally not normative so it can be maintained by the community with less bureaucracy than the normative documents. The comment removal could be part of the commit that fixes the normative context and would only take a few minutes to prepare.

> If 574 is rejected, and that the relationships somehow should be re-introduced/defined in the Vocabulary, only then 566 is useful. My preference would be to leave out the information for the time being instead of introducing information that in all likelihood doesn't belong.

While it's true that we can't predict the future or how long it will take to fix the normative JSON-LD context (this issue has existed for almost 7 years now), we can take action on what we know today. The action I'm proposing is to document the current discrepancies and the expected resolution as comments in the ontology for the benefit of those using it and cross-referencing it to normative documents.

**Pull request closed without merging**
